analytics: {}
color:
  brandColors:
    - '#000000'
    - '#7F7305'
    - '#000000'
    - '#F8E858'
    - '#D8D898'
  brandStrength: 0
  lightness: 0.512335
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.9816805932546375
name: markwaldron
opengraph: {}
purpose: {}
typography_spectrum: 0.37831260036080216
