name: markwaldron
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37831260036080216
title: mark remarked
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7F7305'
    - '#000000'
    - '#F8E858'
    - '#D8D898'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
