analytics: {}
color:
  brandColors:
    - '#C0C8C0'
    - '#000000'
    - '#606050'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.512335
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.9816805932546375
name: markwaldron
opengraph: {}
purpose: {}
typography_spectrum: 0.37831260036080216
